name: Jfrog Trigger minor release in feature to develop
on:
  push:
    branches:
      - lrajula-patch-1

jobs:
  bump-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set next snapshot version
        run: echo "This is a manually triggered workflow."
